-- Comprehensive Schema Rebuild
-- This script drops all existing app-related tables and types to ensure a clean slate,
-- then recreates the entire schema with correct relationships and seeds it with demo data.

-- Step 1: Drop existing objects in reverse order of dependency to avoid errors.
DROP TABLE IF EXISTS public.saved_places CASCADE;
DROP TABLE IF EXISTS public.saved_trips CASCADE;
DROP TABLE IF EXISTS public.city_categories CASCADE;
DROP TABLE IF EXISTS public.location_images CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.days CASCADE;
DROP TABLE IF EXISTS public.cities CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.phrases CASCADE;
DROP TABLE IF EXISTS public.bargaining_price_guide CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP TYPE IF EXISTS public.plan_type CASCADE;
DROP TYPE IF EXISTS public.time_of_day CASCADE;

DROP FUNCTION IF EXISTS public.is_admin();
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Step 2: Create custom types
CREATE TYPE public.plan_type AS ENUM ('free', 'paid');
CREATE TYPE public.time_of_day AS ENUM ('Morning', 'Afternoon', 'Evening', 'Anytime');

-- Step 3: Create profiles table and new user trigger
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  plan_type public.plan_type NOT NULL DEFAULT 'free',
  food_scanner_used integer NOT NULL DEFAULT 0,
  trip_planner_used integer NOT NULL DEFAULT 0
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile." ON public.profiles
  FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Step 4: Create application tables
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL UNIQUE,
  icon text,
  emoji text
);

CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL UNIQUE,
  state text NOT NULL,
  description text,
  short_tagline text,
  thumbnail_url text,
  popularity_score integer DEFAULT 50,
  safety_score integer DEFAULT 5,
  best_time_to_visit text,
  weather_info text
);

CREATE TABLE public.city_categories (
  city_id uuid NOT NULL REFERENCES public.cities(id) ON DELETE CASCADE,
  category_id uuid NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (city_id, category_id)
);

CREATE TABLE public.days (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  city_id uuid NOT NULL REFERENCES public.cities(id) ON DELETE CASCADE,
  day_number integer NOT NULL,
  title text,
  UNIQUE(city_id, day_number)
);

CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  day_id uuid REFERENCES public.days(id) ON DELETE CASCADE,
  timing_tag public.time_of_day,
  name text NOT NULL,
  category text,
  short_intro text,
  image_url text,
  latitude double precision,
  longitude double precision,
  details jsonb,
  UNIQUE(name)
);

CREATE TABLE public.location_images (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  location_id uuid NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  alt_text text
);

CREATE TABLE public.phrases (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  category text NOT NULL,
  en text NOT NULL,
  hi text NOT NULL,
  pronunciation text,
  is_adult boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.bargaining_price_guide (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  location_name text NOT NULL,
  item_name text NOT NULL,
  fair_price_range text,
  quoted_price_range text
);

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.saved_places (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  location_id uuid NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (user_id, location_id)
);

CREATE TABLE public.saved_trips (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  trip_details jsonb
);

-- Step 5: Enable RLS and define policies
CREATE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT (auth.jwt()->>'email') = 'kartikroyal777@gmail.com';
$$;

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.city_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.phrases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bargaining_price_guide ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_trips ENABLE ROW LEVEL SECURITY;

-- Public read access policies
CREATE POLICY "Public can read all" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.cities FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.city_categories FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.days FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.locations FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.location_images FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.phrases FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.bargaining_price_guide FOR SELECT USING (true);
CREATE POLICY "Public can read all" ON public.notifications FOR SELECT USING (true);

-- Admin full access policies
CREATE POLICY "Admins can manage all" ON public.categories FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.cities FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.city_categories FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.days FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.locations FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.location_images FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.phrases FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.bargaining_price_guide FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all" ON public.notifications FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- User-specific policies
CREATE POLICY "Users can manage their own saved places" ON public.saved_places FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage their own saved trips" ON public.saved_trips FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Step 6: Seed initial data
DO $$
DECLARE
  udaipur_id uuid;
  jaipur_id uuid;
  delhi_id uuid;
  day1_id uuid;
  day2_id uuid;
  city_palace_id uuid;
  forts_cat_id uuid;
  lakes_cat_id uuid;
  heritage_cat_id uuid;
BEGIN
  -- Seed Categories
  INSERT INTO public.categories (name, icon, emoji) VALUES
    ('Forts & Palaces', 'castle', '🏰'),
    ('Lakes & Rivers', 'waves', '🌊'),
    ('Gardens', 'trees', '🌳'),
    ('Temples', 'building', '🛕'),
    ('Markets', 'shopping-bag', '🛍️'),
    ('Heritage', 'landmark', '🏛️')
  ON CONFLICT (name) DO NOTHING;

  SELECT id INTO forts_cat_id FROM public.categories WHERE name = 'Forts & Palaces';
  SELECT id INTO lakes_cat_id FROM public.categories WHERE name = 'Lakes & Rivers';
  SELECT id INTO heritage_cat_id FROM public.categories WHERE name = 'Heritage';

  -- Seed Cities
  INSERT INTO public.cities (name, state, description, short_tagline, thumbnail_url, popularity_score, safety_score, best_time_to_visit) VALUES
    ('Udaipur', 'Rajasthan', 'The city of lakes, known for its romantic palaces and vibrant culture.', 'Venice of the East', 'https://images.unsplash.com/photo-1599661046289-e31897846364?w=800&h=600&fit=crop', 94, 9, 'Sep - Mar'),
    ('Jaipur', 'Rajasthan', 'The Pink City, a hub of royal history, grand forts, and bustling markets.', 'The Pink City', 'https://images.unsplash.com/photo-1603262339346-d8c29a8a015c?w=800&h=600&fit=crop', 92, 8, 'Oct - Mar'),
    ('Delhi', 'Delhi', 'India''s capital, a sprawling metropolis blending ancient history with modernity.', 'The Heart of India', 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&h=600&fit=crop', 93, 7, 'Oct - Mar')
  ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name RETURNING id INTO udaipur_id, jaipur_id, delhi_id;

  SELECT id INTO udaipur_id FROM public.cities WHERE name = 'Udaipur';
  SELECT id INTO jaipur_id FROM public.cities WHERE name = 'Jaipur';
  SELECT id INTO delhi_id FROM public.cities WHERE name = 'Delhi';

  -- Link categories to cities
  INSERT INTO public.city_categories (city_id, category_id) VALUES
    (udaipur_id, forts_cat_id), (udaipur_id, lakes_cat_id), (udaipur_id, heritage_cat_id),
    (jaipur_id, forts_cat_id), (jaipur_id, heritage_cat_id),
    (delhi_id, heritage_cat_id)
  ON CONFLICT DO NOTHING;

  -- Seed Days for Udaipur
  INSERT INTO public.days (city_id, day_number, title) VALUES
    (udaipur_id, 1, 'Royal Palaces & Lakeside Charm'),
    (udaipur_id, 2, 'Cultural Immersion & Sunset Views')
  ON CONFLICT (city_id, day_number) DO UPDATE SET title = EXCLUDED.title RETURNING id INTO day1_id, day2_id;
  
  SELECT id INTO day1_id FROM public.days WHERE city_id = udaipur_id AND day_number = 1;

  -- Seed City Palace Location for Udaipur Day 1
  INSERT INTO public.locations (day_id, timing_tag, name, category, short_intro, image_url, latitude, longitude, details)
  VALUES (
      day1_id,
      'Morning',
      'City Palace',
      'Royal Palace',
      'A majestic palace complex on the banks of Lake Pichola, showcasing a blend of Rajasthani and Mughal architectural styles.',
      'https://images.unsplash.com/photo-1577154415519-571f045b4a49?w=800&h=600&fit=crop',
      24.5762,
      73.6835,
      '{"about": {"historical_background": "Built over a period of nearly 400 years, with contributions from several rulers of the Mewar dynasty. Construction began in 1553 by Maharana Udai Singh II.", "cultural_significance": "It is the heart of Udaipur and a symbol of the Mewar kingdom''s power and prestige. The palace is still partially owned by the royal family.", "why_famous": "Famous for its intricate architecture, sprawling courtyards, and the stunning views it offers of Lake Pichola and the surrounding city."}, "opening_hours": {"daily_timings": {"open": "09:30 AM", "close": "05:30 PM"}, "weekly_closures": [], "seasonal_changes": "Timings might change during festivals."}, "best_time_to_visit": {"best_season": "Winter (October - March)", "best_time_of_day": "Morning to avoid crowds and heat.", "festival_timing": "Holi and Diwali are celebrated with grandeur."}, "transport": {"nearest_airport": "Maharana Pratap Airport (UDR), 22km", "nearest_railway_station": "Udaipur City Railway Station, 3km", "last_mile_options": "Auto-rickshaws and taxis are readily available. It is located in the old city, accessible by narrow lanes.", "taxi_cost_estimate": "₹150-200 from the railway station."}, "safety_risks": {"safety_score": 9, "scams_warnings": ["Beware of unofficial guides at the entrance.", "Some shops inside may be overpriced."], "womens_safety_rating": "High", "emergency_contacts": [{"name": "Tourist Police", "number": "1363"}]}, "cultural_etiquette": {"dress_code": "Respectful attire is recommended; cover shoulders and knees.", "dos_donts": ["Do hire an official audio guide.", "Don''t touch the artifacts."], "temple_etiquette": "Remove shoes before entering small shrines within the complex.", "photography_rules": "Photography is allowed, but may require an extra fee for video cameras."}, "costs_money": {"ticket_prices": {"local": "₹30", "foreigner": "₹300"}, "avg_budget_per_day": "₹500-700 per person (including tickets and guide).", "haggling_info": "Not applicable for tickets, but required for souvenirs outside.", "digital_payment_availability": "Yes, at the ticket counter."}, "amenities": {"toilets": "Available, but can be crowded.", "wifi": "Not available.", "seating": "Available in courtyards.", "water_refills": "Available for purchase.", "cloakrooms": "Available near the entrance."}, "hygiene_index": {"rating": 4, "notes": "Well-maintained premises."}, "guides": {"availability": "Official guides and audio guides available.", "booking_info": "Available at the entrance."}, "map_navigation": {"google_maps_link": "https://goo.gl/maps/qE5gS3aJmSq1z5d5A"}, "events_festivals": {"event_name": "Holika Dahan Ceremony", "event_date": "March (eve of Holi)", "type": "Cultural"}, "things_to_do": {"main_activities": ["Explore the museum", "Visit the Crystal Gallery", "Enjoy the view of Lake Pichola", "See the vintage car collection."], "nearby_attractions": ["Jagdish Temple", "Bagore Ki Haveli"]}, "photo_spots": [{"title": "Tripolia Gate View", "description": "Classic shot of the palace entrance.", "image_url": "https://images.unsplash.com/photo-1621363613613-3942ad268953?w=400&h=300", "map_link": ""}, {"title": "Mor Chowk (Peacock Courtyard)", "description": "Famous for its intricate glass mosaics of peacocks.", "image_url": "https://images.unsplash.com/photo-1603813693370-97495a2306a4?w=400&h=300", "map_link": ""}], "recommended_restaurants": [], "recommended_hotels": [], "local_foods": [], "influencer_videos": []}'::jsonb
  )
  ON CONFLICT (name) DO NOTHING RETURNING id INTO city_palace_id;
  
  -- Seed images for City Palace
  INSERT INTO public.location_images (location_id, image_url, alt_text) VALUES
    (city_palace_id, 'https://images.unsplash.com/photo-1541344440821-863933482f3a?w=800&h=600', 'View of City Palace from Lake Pichola'),
    (city_palace_id, 'https://images.unsplash.com/photo-1621363613613-3942ad268953?w=800&h=600', 'Intricate interior of City Palace')
  ON CONFLICT DO NOTHING;

END $$;
