-- Comprehensive Schema Rebuild and Data Seeding
-- This script safely drops the old schema and rebuilds it correctly.

-- Step 1: Drop existing objects in the correct order to avoid dependency errors.
DROP TABLE IF EXISTS public.saved_places CASCADE;
DROP TABLE IF EXISTS public.saved_trips CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.location_images CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.days CASCADE;
DROP TABLE IF EXISTS public.city_categories CASCADE;
DROP TABLE IF EXISTS public.cities CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.phrases CASCADE;
DROP TABLE IF EXISTS public.bargaining_price_guide CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Drop dependent types and functions after tables are gone.
DROP TYPE IF EXISTS public.plan_type;
DROP TYPE IF EXISTS public.time_of_day;
DROP FUNCTION IF EXISTS public.is_admin();
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Step 2: Create the is_admin function first.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT TRUE FROM public.profiles WHERE id = auth.uid() AND is_admin = TRUE),
    FALSE
  );
$$;

-- Step 3: Create custom types (ENUMs).
CREATE TYPE public.plan_type AS ENUM ('free', 'paid');
CREATE TYPE public.time_of_day AS ENUM ('Morning', 'Afternoon', 'Evening', 'Anytime');

-- Step 4: Recreate tables with the correct structure.
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at timestamptz,
  full_name text,
  avatar_url text,
  is_admin boolean DEFAULT false,
  plan_type public.plan_type DEFAULT 'free'::public.plan_type NOT NULL,
  food_scanner_used integer DEFAULT 0 NOT NULL,
  trip_planner_used integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL UNIQUE,
  icon text,
  emoji text
);

CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL UNIQUE,
  state text,
  description text,
  short_tagline text,
  thumbnail_url text,
  popularity_score integer,
  safety_score integer,
  best_time_to_visit text,
  weather_info text
);

CREATE TABLE public.city_categories (
  city_id uuid NOT NULL REFERENCES public.cities(id) ON DELETE CASCADE,
  category_id uuid NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (city_id, category_id)
);

CREATE TABLE public.days (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  city_id uuid NOT NULL REFERENCES public.cities(id) ON DELETE CASCADE,
  day_number integer NOT NULL,
  title text,
  UNIQUE (city_id, day_number)
);

CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  day_id uuid REFERENCES public.days(id) ON DELETE CASCADE,
  timing_tag public.time_of_day,
  name text NOT NULL UNIQUE,
  category text,
  short_intro text,
  image_url text,
  latitude numeric,
  longitude numeric,
  details jsonb
);

CREATE TABLE public.location_images (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  location_id uuid NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  image_url text,
  alt_text text
);

CREATE TABLE public.saved_places (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  location_id uuid NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY (user_id, location_id)
);

CREATE TABLE public.saved_trips (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trip_details jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  message text,
  type text,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.phrases (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  category text NOT NULL,
  en text NOT NULL,
  hi text NOT NULL,
  pronunciation text,
  is_adult boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.bargaining_price_guide (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  location_name text NOT NULL,
  item_name text NOT NULL,
  fair_price_range text,
  quoted_price_range text
);

-- Step 5: Set up Row Level Security (RLS) with corrected policy syntax.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Public tables can be read by anyone
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.cities FOR SELECT USING (true);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.categories FOR SELECT USING (true);
ALTER TABLE public.city_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.city_categories FOR SELECT USING (true);
ALTER TABLE public.days ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.days FOR SELECT USING (true);
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.locations FOR SELECT USING (true);
ALTER TABLE public.location_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.location_images FOR SELECT USING (true);
ALTER TABLE public.phrases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.phrases FOR SELECT USING (true);
ALTER TABLE public.bargaining_price_guide ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.bargaining_price_guide FOR SELECT USING (true);

-- Authenticated users can manage their own saved places and trips
ALTER TABLE public.saved_places ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own saved places" ON public.saved_places FOR ALL USING (auth.uid() = user_id);
ALTER TABLE public.saved_trips ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own saved trips" ON public.saved_trips FOR ALL USING (auth.uid() = user_id);

-- Notifications are readable by all authenticated users
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow authenticated read access" ON public.notifications FOR SELECT TO authenticated USING (true);

-- Admins get full access to everything
CREATE POLICY "Allow admin full access" ON public.cities FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.categories FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.city_categories FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.days FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.locations FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.location_images FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.phrases FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.bargaining_price_guide FOR ALL USING (public.is_admin());
CREATE POLICY "Allow admin full access" ON public.notifications FOR ALL USING (public.is_admin());

-- Step 6: Create a trigger to auto-create profiles for new users.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Step 7: Seed the database with rich, detailed data.
DO $$
DECLARE
  city_udaipur_id uuid;
  city_jaipur_id uuid;
  day1_udaipur_id uuid;
  day2_udaipur_id uuid;
  day1_jaipur_id uuid;
  loc_city_palace_id uuid;
  loc_pichola_id uuid;
  loc_saheliyon_id uuid;
  loc_hawa_mahal_id uuid;
  cat_heritage_id uuid;
  cat_lakes_id uuid;
  cat_gardens_id uuid;
BEGIN
  -- Seed Categories
  INSERT INTO public.categories (name, icon, emoji) VALUES ('Heritage', 'castle', '🏰'), ('Lakes', 'waves', '🌊'), ('Gardens', 'trees', '🌳')
  ON CONFLICT (name) DO NOTHING
  RETURNING id, id, id INTO cat_heritage_id, cat_lakes_id, cat_gardens_id;
  SELECT id INTO cat_heritage_id FROM public.categories WHERE name = 'Heritage';
  SELECT id INTO cat_lakes_id FROM public.categories WHERE name = 'Lakes';
  SELECT id INTO cat_gardens_id FROM public.categories WHERE name = 'Gardens';

  -- Seed Cities
  INSERT INTO public.cities (name, state, description, short_tagline, thumbnail_url, popularity_score, safety_score, best_time_to_visit, weather_info) VALUES
  ('Udaipur', 'Rajasthan', 'Often called the "Venice of the East," Udaipur is famous for its romantic lakes and royal palaces.', 'The City of Lakes', 'https://images.unsplash.com/photo-1599661046289-e31897846364?w=800&h=600&fit=crop', 94, 9, 'September to March', 'Pleasant winters, hot summers.'),
  ('Jaipur', 'Rajasthan', 'The vibrant Pink City, known for its stunning forts, palaces, and bustling bazaars.', 'The Pink City', 'https://images.unsplash.com/photo-1603262339346-d8c29a8a015c?w=800&h=600&fit=crop', 92, 8, 'October to March', 'Cool winters, very hot summers.')
  ON CONFLICT (name) DO NOTHING;

  SELECT id INTO city_udaipur_id FROM public.cities WHERE name = 'Udaipur';
  SELECT id INTO city_jaipur_id FROM public.cities WHERE name = 'Jaipur';

  -- Link categories to cities
  INSERT INTO public.city_categories (city_id, category_id) VALUES (city_udaipur_id, cat_heritage_id), (city_udaipur_id, cat_lakes_id), (city_jaipur_id, cat_heritage_id) ON CONFLICT DO NOTHING;

  -- Seed Days
  INSERT INTO public.days (city_id, day_number, title) VALUES
  (city_udaipur_id, 1, 'Royal Palaces & Lake Views'),
  (city_udaipur_id, 2, 'Gardens & Cultural Evening'),
  (city_jaipur_id, 1, 'The Pink City''s Grandeur')
  ON CONFLICT (city_id, day_number) DO NOTHING;

  SELECT id INTO day1_udaipur_id FROM public.days WHERE city_id = city_udaipur_id AND day_number = 1;
  SELECT id INTO day2_udaipur_id FROM public.days WHERE city_id = city_udaipur_id AND day_number = 2;
  SELECT id INTO day1_jaipur_id FROM public.days WHERE city_id = city_jaipur_id AND day_number = 1;

  -- Seed Locations
  INSERT INTO public.locations (day_id, timing_tag, name, category, short_intro, image_url, latitude, longitude, details) VALUES 
  (
    day1_udaipur_id, 'Morning', 'City Palace', 'Royal Palace', 'A majestic palace complex on the banks of Lake Pichola, showcasing a blend of Rajasthani and Mughal architectural styles.', 'https://images.unsplash.com/photo-1577154415519-571f045b4a49?w=800&h=600&fit=crop', 24.5762, 73.6835,
    '{ "about": { "historical_background": "Built over 400 years, with contributions from several rulers of the Mewar dynasty. Construction began in 1553 by Maharana Udai Singh II.", "cultural_significance": "The heart of Udaipur and a symbol of the Mewar kingdom''s power. It''s a complex of several palaces, courtyards and gardens.", "why_famous": "Famous for its intricate architecture, sprawling courtyards, and the stunning views it offers of Lake Pichola." }, "opening_hours": { "daily_timings": {"open": "09:30 AM", "close": "05:30 PM"}, "weekly_closures": [], "seasonal_changes": "Timings might change during festivals." }, "best_time_to_visit": { "best_season": "Winter (October - March)", "best_time_of_day": "Morning to avoid crowds.", "festival_timing": "Holi and Diwali are celebrated with grandeur." }, "transport": { "nearest_airport": "Maharana Pratap Airport (UDR), 22km", "nearest_railway_station": "Udaipur City Railway Station, 3km", "last_mile_options": "Auto-rickshaws and taxis are readily available.", "taxi_cost_estimate": "₹150-200 from the railway station." }, "safety_risks": { "safety_score": 9, "scams_warnings": ["Beware of unofficial guides at the entrance.", "Some shops inside may be overpriced."], "womens_safety_rating": "High", "emergency_contacts": [{"name": "Tourist Police", "number": "1363"}] }, "cultural_etiquette": { "dress_code": "Respectful attire is recommended.", "dos_donts": ["Do hire an official audio guide.", "Don''t touch the artifacts."], "temple_etiquette": "Remove shoes before entering small shrines.", "photography_rules": "Photography is allowed, extra fee for video." }, "costs_money": { "ticket_prices": { "local": "₹30", "foreigner": "₹300" }, "avg_budget_per_day": "₹700 per person", "haggling_info": "Not for tickets, but for souvenirs outside.", "digital_payment_availability": "Yes, at the ticket counter." }, "amenities": { "toilets": "Available, can be crowded.", "wifi": "Not available.", "seating": "Available in courtyards.", "water_refills": "Available for purchase.", "cloakrooms": "Available near the entrance." }, "photo_spots": [ {"title": "Tripolia Gate View", "description": "Classic shot of the palace entrance.", "image_url": "https://images.unsplash.com/photo-1621363613613-3942ad268953?w=400&h=300&fit=crop"}, {"title": "Mor Chowk (Peacock Courtyard)", "description": "Famous for its intricate glass mosaics of peacocks.", "image_url": "https://images.unsplash.com/photo-1603813693370-97495a2306a4?w=400&h=300&fit=crop"} ], "influencer_videos": [{"title": "A Tour of Udaipur''s City Palace", "video_id": "dQw4w9WgXcQ", "influencer_name": "Travel Explorer"}] }'::jsonb
  ),
  (
    day1_udaipur_id, 'Evening', 'Lake Pichola', 'Lake', 'An artificial fresh water lake, created in the year 1362 AD, named after the nearby Picholi village.', 'https://images.unsplash.com/photo-1596709535345-c1e17d2371da?w=800&h=600&fit=crop', 24.57, 73.68,
    '{ "about": { "historical_background": "Created in 1362 AD, it was later expanded by Maharana Udai Singh II. The lake has four islands: Jag Niwas, Jag Mandir, Mohan Mandir, and Arsi Vilas.", "why_famous": "Known for its scenic beauty and the palaces that dot its islands and shores, especially the Lake Palace." }, "best_time_to_visit": { "best_time_of_day": "Sunset for boat rides." }, "things_to_do": { "main_activities": ["Take a boat ride", "Watch the sunset from Ambrai Ghat", "Dine at a lakeside restaurant."] } }'::jsonb
  ),
  (
    day2_udaipur_id, 'Morning', 'Saheliyon Ki Bari', 'Garden', 'A beautiful garden and a popular tourist space in Udaipur, built for the queen and her royal friends.', 'https://images.unsplash.com/photo-1628142263164-68f15b7a5e44?w=800&h=600&fit=crop', 24.602, 73.688,
    '{}'::jsonb
  ),
  (
    day1_jaipur_id, 'Morning', 'Hawa Mahal', 'Palace', 'A palace of winds with 953 windows, allowing royal women to observe street festivities unseen.', 'https://images.unsplash.com/photo-1603262339346-d8c29a8a015c?w=800&h=600&fit=crop', 26.9239, 75.8267,
    '{}'::jsonb
  )
  ON CONFLICT (name) DO NOTHING
  RETURNING id, id, id, id INTO loc_city_palace_id, loc_pichola_id, loc_saheliyon_id, loc_hawa_mahal_id;

  -- Seed Location Images
  INSERT INTO public.location_images (location_id, image_url) VALUES
  (loc_city_palace_id, 'https://images.unsplash.com/photo-1542649276-37a4d78036d3?w=800&h=600&fit=crop'),
  (loc_city_palace_id, 'https://images.unsplash.com/photo-1617594232302-702374dfce36?w=800&h=600&fit=crop');

END $$;
